lang: en

# Economy Settings (Wages per minute)
wages:
  miner: 10.0
  guard: 15.0
  farmer: 8.0
  hunter: 12.0
  lumberjack: 9.0
  fisherman: 9.0

# Job Settings
jobs:
  farmer:
    chance: 10 # Percentage chance per 5 seconds
    items:
      - WHEAT
      - CARROT
      - POTATO
      - BEETROOT
  miner:
    chance: 5
    items:
      - COBBLESTONE
      - COAL
      - RAW_IRON
      - RAW_COPPER
  hunter:
    chance: 5
    items:
      - BEEF
      - PORKCHOP
      - CHICKEN
      - LEATHER
  lumberjack:
    chance: 8
    items:
      - OAK_LOG
      - BIRCH_LOG
      - STICK
      - APPLE
  fisherman:
    chance: 8
    items:
      - COD
      - SALMON
      - TROPICAL_FISH
      - PUFFERFISH
      - NAUTILUS_SHELL
