lang: en

# Economy Settings (Wages per minute)
wages:
  miner: 10.0
  guard: 15.0
  farmer: 8.0
  hunter: 12.0

# Job Settings
jobs:
  farmer:
    chance: 10 # Percentage chance per 5 seconds
    items:
      - WHEAT
      - CARROT
      - POTATO
      - BEETROOT
  miner:
    chance: 5
    items:
      - COBBLESTONE
      - COAL
      - RAW_IRON
      - RAW_COPPER
  hunter:
    chance: 5
    items:
      - BEEF
      - PORKCHOP
      - CHICKEN
      - LEATHER
